@startuml
hide footbox
participant "Client" as Client
participant "Server" as Server
activate "Client"
activate "Server"
"Client" -> "Server" : 1. Go Query [domain-Y]
"Server" --> "Client" : 2. Go Response [domain-Y]
deactivate "Client"
deactivate "Server"
@enduml
