@startuml
skinparam svgDimensionStyle false
hide footbox
participant "Client" as Client
participant "Server" as Server
activate "Client"
"Client" -> "Server" : 1. Go Query [domain-YY]
activate "Server"
"Server" --> "Client" : 2. Go Response [domain-YY]
deactivate "Client"
deactivate "Server"
@enduml
