@startuml
package "IHE Supplement" {

package "Volume 6: test plan" as v6 {
package "coverage plan" #Chocolate{
}
package "unit tests" #Chocolate{
}
package "integration tests" #Chocolate{
}
}


package "Volume 5: Artifacts" as v5 #TECHNOLOGY {
card vocabulary #Purple {
}
card valueSet #Purple {
}
card conceptMap #Purple {
}
card structureDefinition #Purple {
}
card capabilityStatement #Purple {
}
}

package "Volume 3: Content" as v3 #IMPLEMENTATION {
package Content-1 #YellowGreen {
}
}

package "Volume 2: Transactions" as v2 #IMPLEMENTATION {
package Transaction-1 #IMPLEMENTATION {
package message-1 {
card "Trigger Events" #YellowGreen {
}
card "Message Encoding" #YellowGreen {
}
card "Expected Actions" #YellowGreen {
}
}
}
}

package "Volume 4: National Extensions" as v4 {
Package USA #DeepSkyBlue {
}
package France #Tomato {
}
}

package "Volume 1: Use-Case Definition" as v1 #APPLICATION {

  card "Grouping Behavior" as gb  #BUSINESS{
}
  card "Security Considerations" as sc #BUSINESS{
}
  card Options  #BUSINESS{
}
  card Transactions  #BUSINESS{
}
  card Actors  #BUSINESS{
}
}

top to bottom direction
v1 --[hidden]> v2
v1 --[hidden]> v3
v2 --[hidden]> v5
v3 --[hidden]> v5
v5 --[hidden]> v4
v5 --[hidden]> v6
}
@enduml